# PPythonSoc: NumPy & Matplotlib
Wednesday 9th November 2022

### Meeting ID: 853 5999 9098
### Passcode: 886017


> Q1: How do you plot on a computer?



e.g. trajectory of a ball thrown in the air...?


<img src='ball_thrown_in_air.png' width="1000" height="300">


> A1: MATPLOTLIB!

> Q2: How should we store the position/time arrays?

> A2: NUMPY!

### NumPy:
* Creating arrays
* Manipulating arrays
* Cheeky tricks and built in functionality

### Matplotlib:
Lots of ways of doing the same thing...
* General way for plotting

(lots of copy and pasting...)

In [1]:
### import numpy!
import numpy as np

np.array([1,2,3])


array([1, 2, 3])

In [2]:
# To create numpy arrays, pass an 'iterable' to np.array() method
a = np.array([1, 2, 3])
print(a)


[1 2 3]


^^ Looks an awful lot like a list, but NumPy arrays are really good at <b><i>MAFFS</i></b>

In [9]:
b = np.array([4,5,6])
a = np.array([1,2,3])
## Add/subtract/divide/mulitply/raise to a power two arrays


## Try do this with a list normy
[1,2,3] ** 2
 



TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Linspaces and Aranges!!

In [15]:
## arange - given SPACING!
myArange = np.arange(0, 10, 0.5)



## linspace - given QUANTITY!
myLinspace = np.linspace(0, 10, 20, endpoint=False)
print(myLinspace)




[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


#### Indexing and Broadcasting

In [25]:
### How do I get the i'th item in an array?
a = np.linspace(0, 20, 5)
print(a)

# Items over 10?
print(a[a > 10])






[ 0.  5. 10. 15. 20.]
[15. 20.]


In [28]:
### Changing values - BROADCASTING
print(a)

a[:2] = 0

print(a)




[ 0.  5. 10. 15.  0.]
[ 0.  0. 10. 15.  0.]


## Multi-dimensional arrays

* 1D array: each item referenced by one index
* 2D array: each item referenced by TWO indices (which row? which column?)
* 3D array: etc...


In [29]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

ROWS, then COLUMNS

In [37]:
### Accessing each item.. Specify two indices
print(twoD[0,:])

## By condition...
print(twoD[twoD>5])




[1 2 3]
[6 7 8 9]


## Plot Trajectory of Thrown Ball

Santa throws a ball with initial velocity $ u $ at angle $\alpha$ to the ground. Plot the trajectory!


<img src="santa_throwing.png" width=1000 height=300>

Suppose that when the ball hits the floor (y = 0), it stops moving immediately.

### Plan:
* Initialise a position array

Use a 2D array, where the first column holds $x$ coordinates, the second column holds $y$ coordinates. Each row then records the $(x,y)$ position vector of the ball at each time!



* Initialise the time array, over which we want to calculate the position of the ball

Can just be a good old 1D array

* Define constants, then do the maths!

* Find time when the ball hits the ground (y = 0), then change all other values of (x,y) hereafter.

Because the ball stops dead

In [ ]:
## Initialise position and time array
nTimeSteps = 100
r = np.zeros((nTimeSteps, 2))
t = np.linspace(0, 2, nTimeSteps)

# Define constants
alpha = np.pi/6
u = 5
g = 9.81




In [ ]:
### Do the maths
r[:,0] = u*np.cos(alpha) * t
r[:,1] = u*np.cos(alpha)*t - 1/2 * g * t**2 + 1

# check when the ball hits the floor?
i = int(np.argwhere(r[:,1]>0)[-1])
r[i+1:,0] = r[i,0]
r[i+1:,1] = r[i,1]





In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(20,10))
ax = fig.add_subplot(111)

ax.plot([-1,10],[0,0], 'k')
ax.set_xlim(0, 10)
ax.plot(r[:,0],r[:,1])

# ax.legend()
plt.show()
