## Poynting's Python Society
Sunday 24th October 2021


### What are programming languages and how does Python work?


<img src='coding3.png' width="2000" height="500">

* Interpreter languages translate syntax into machine code 'on-the-go' - i.e. whilst the script is running
  * e.g. Python
* Compiler languages translate syntax into machine code before actually running
  * e.g. C++

### Data Types:

* Strings: a sequence of characters


In [2]:
myString = 'fizix'


print(myString)




fizix


Some useful features:

In [3]:
# escape and special characters
# e.g. newline : '\n'
myString = '*******\n\tfizix\n*******'
print(myString)


*******
	fizix
*******


Indexing & Slicing:

`var[n:m:p]`

n: starting position    |    m: ending position (exclusive)    |    p: step

In [13]:
# indexing & slicing:
myString = 'fizix'
# print first character
myString[0]



'f'

In [14]:
# print last character
print(myString[-5])


f


In [19]:
print(myString[0:3])
 

fiz


In [26]:
# replacement
myString = 'fizix'
myString2 = myString.replace('f', 'p')
print(myString2)



pizix


In [30]:
myString = 'fizix'
print(myString.upper())


FIZIX


### Data Types:
* Lists: Ordered collection of objects - does what it says on the tin

In [35]:
# can contain any data types or objects
myList = [0.1, [0, 1], 'str']
print(myList)


[0.1, [0, 1], 'str']


In [39]:
# indexing works exactly the same!
myList = ['p', 'h', 'y', 's', 'i', 'c', 's']

print(myList[0:3])
    

['p', 'h', 'y']


In [42]:
# list objects support 'item assignment'
myList[-1] = 'z'
print(myList)


['p', 'h', 'y', 's', 'i', 'c', 'z']


In [49]:
# help(list)
myList = [1,2,3]
myList.append(4)

print(myList)


[1, 2, 3, 4]


### NUMPY ARRAYS

<img src='numpy.png' width="1000" height="300">

* NumPy is a really popular package in Python
* Good at handling vectors and matrices in the form of `np.ndarray`'s

In [2]:
# import numpy
import numpy as np


In [58]:
# To create numpy arrays, pass an 'iterable' to np.array() method  


* Lists were essentially 1D: an ordered collection of items

* Numpy arrays can be multi-dimensional...

In [57]:
# 1d array - boring af
oneDArray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
oneDArray


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# 2d array - big wow
twoDArray = np.array([[0, 1, 2], [3, 4, 5]])
print(twoDArray)


[[0 1 2]
 [3 4 5]]


In [69]:
# special array types
myArray = np.zeros((5, 5))
print(myArray)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [83]:
# Apply numpy methods to arrays...
# e.g. summing elements of an array:
myArray = np.array([[0, 1, 2],[3,4,5]])


### Indexing NumPy arrays:

* Exactly the same as indexing lists or strings, except this time we need to account for indexing OVER DIFFERENT DIMENSIONS


\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{bmatrix}

e.g.
$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

In [102]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
# indexing
mat[mat<2]


array([1])

In [106]:
# broadcasting
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat, '\n\n')
mat[mat>4]=1
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 


[[1 2 3]
 [4 1 1]
 [1 1 1]]


In [120]:
# array manipulations
myArray2 = np.array([[1, 2, 3],[4, 5, 6]])
myArray3 = np.array([1, 2])




In [121]:
[i for i in range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
a = np.array([1, 2, 3])
b = np.array([1,2,3])
a * b

array([1, 4, 9])

14